name: CI/CD Pileline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: choij1589/private-el9:full
      options: --user root --workdir /github/workspace

    steps:
      - name: Setup SSH for CERN GitLab
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 7999 gitlab.cern.ch >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh -T git@gitlab.cern.ch -p 7999 || true
          
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: true
          
      - name: Run setup.sh
        run: source setup.sh

      - name: Build project
        run: ./scripts/build.sh
