name: CI/CD Pileline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: choij1589/private-el9:full
      options: --user root --workdir /github/workspace

    steps:
      - name: Checkout Code
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-kye: ${{ secrets.SSH_PRIVATE_KYE }}
          submodules: true
          
      - name: Fetch Submodules
        run: |
          git config --global --add safe.directory /__w/SKNanoAnalyzer/SKNanoAnalyzer
          git submodule update --init --recursive
          
      - name: Run setup.sh
        run: source setup.sh

      - name: Build project
        run: ./scripts/build.sh
