name: CI/CD Pileline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: choij1589/private-el9:full
      options: --user root
      env:
        USER: root

    steps:
      - name: Setup SSH for CERN GitLab
        run: |
          mkdir -p /root/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /root/.ssh/id_rsa
          chmod 600 /root/.ssh/id_rsa
          ssh-keyscan -p 7999 gitlab.cern.ch >> /root/.ssh/known_hosts
          chmod 644 /root/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add /root/.ssh/id_rsa
          ssh -T git@gitlab.cern.ch -p 7999 || true
          
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Run setup.sh
        run: |
          echo $USER
          echo $GITHUB_ACTION
          chmod 755 setup.sh && ./setup.sh

      - name: Build project
        run: ./scripts/build.sh
